title: Hailu Xu
description: Assistant Professor at California State University, Long Beach
url: "https://andrewxu22.github.io"
baseurl: ""

author:
  name: Hailu Xu
  title: Assistant Professor
  department: Department of Computer Engineering & Computer Science
  university: California State University, Long Beach
  email: hailu.xu [at] csulb.edu
  address: "250 Bellflower Blvd, Long Beach, CA 90840"
  google_scholar: "https://scholar.google.com/citations?hl=en&user=E7ahZH8AAAAJ&view_op=list_works&sortby=pubdate"
  research_gate: "https://www.researchgate.net/profile/Hailu_Xu"
  cv: "https://drive.google.com/file/d/1I_vpA6tFBLXzQ7XJv0Zc9LqcGrMAhMHa/view?usp=share_link"

permalink: /:title/

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
